import { aboutContent } from '@/src/data/about';
import { PageChrome, PageCta } from '@/src/components/PageChrome';
import type { Metadata } from 'next';
import { contactById } from '@/src/data/contact';
import { siteConfig } from '@/src/data/site-config';

export const metadata: Metadata = { title: 'Despre noi | Dariana & Lucia', description: 'Află mai multe despre Dariana, Lash Artist, și Lucia, Nail Artist, și serviciile lor din Giroc, Timiș.' };

export default function AboutPage() { return <PageChrome><main className="inner-page about-page"><header className="inner-page-heading"><p className="section-kicker">Dariana &amp; Lucia</p><h1>{aboutContent.title}</h1><p>{aboutContent.intro}</p></header><section className="specialist-grid" aria-label="Specialiști">{aboutContent.specialists.map((specialist) => { const contact = contactById[specialist.name.toLowerCase() as 'dariana' | 'lucia']; return <article className="specialist-card" key={specialist.name}><p className="specialist-role">{specialist.role}</p><h2>{specialist.name}</h2><p>{specialist.description}</p><p className="card-schedule">{siteConfig.scheduleLabel}</p><div className="card-contact-links"><a href={`tel:${contact.phone}`} aria-label={`Sună la ${contact.name}`}>{contact.displayPhone}</a><a href={contact.whatsapp} target="_blank" rel="noopener noreferrer" aria-label={`Trimite mesaj pe WhatsApp ${contact.name === 'Dariana' ? 'Darianei' : 'Luciei'}`}>WhatsApp</a></div><div className="card-actions"><a className="button button-outline" href={specialist.serviceHref}>{specialist.serviceLabel} <span aria-hidden="true">↗</span></a><a className="button button-primary" href={specialist.bookingHref}>{specialist.bookingLabel} <span aria-hidden="true">↗</span></a></div></article>; })}</section><section className="values-section" aria-labelledby="values-title"><div className="section-heading"><p className="section-kicker">Valorile noastre</p><h2 id="values-title">Un ritual construit cu grijă.</h2></div><div className="value-grid">{aboutContent.values.map((value) => <article className="value-card" key={value.title}><span className="benefit-icon benefit-icon-detail" aria-hidden="true" /><h3>{value.title}</h3><p>{value.description}</p></article>)}</div></section><PageCta /></main></PageChrome>; }
