import type { Metadata } from 'next';
import { PageChrome, PageCta } from '@/src/components/PageChrome';
import { locations } from '@/src/data/locations';
import { pageCopy } from '@/src/data/page-copy';
import { contactById } from '@/src/data/contact';
import { siteConfig } from '@/src/data/site-config';

export const metadata: Metadata = { title: 'Contact și locații | Dariana & Lucia', description: 'Vezi locațiile pentru servicii de gene și unghii din Giroc și continuă către programare.' };

export default function ContactPage() { return <PageChrome><main className="inner-page contact-page"><header className="inner-page-heading"><p className="section-kicker">Dariana &amp; Lucia</p><h1>{pageCopy.contact.title}</h1><p>{pageCopy.contact.intro}</p></header><div className="contact-locations">{locations.map((location) => { const contact = contactById[location.category === 'gene' ? 'dariana' : 'lucia']; return <article className={`contact-location-card location-card-${location.category}`} key={location.id}><p className="location-specialist">{contact.name} · {contact.service}</p><h2>{contact.name} — {contact.service}</h2><p>{pageCopy.contact.locationDescriptions[location.category]}</p><address>{location.address}</address><p className="contact-schedule">{siteConfig.scheduleLabel}</p><div className="contact-details"><a href={`tel:${contact.phone}`} aria-label={`Sună la ${contact.name}`}><span>Telefon</span>{contact.displayPhone}</a><a href={contact.whatsapp} target="_blank" rel="noopener noreferrer" aria-label={`Trimite mesaj pe WhatsApp ${contact.name === 'Dariana' ? 'Darianei' : 'Luciei'}`}><span>WhatsApp</span>Scrie-ne</a>{contact.instagram && <a href={contact.instagram} target="_blank" rel="noopener noreferrer" aria-label={`Deschide profilul Instagram al ${contact.name}`}><span>Instagram</span>@lashesby.dariana28</a>}{contact.tiktok && <a href={contact.tiktok} target="_blank" rel="noopener noreferrer" aria-label={`Deschide profilul TikTok al ${contact.name}`}><span>TikTok</span>@lashesby_dariana</a>}</div><div className="card-actions"><a className="button button-primary" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location.mapsQuery)}`} target="_blank" rel="noopener noreferrer" aria-label={`Deschide locația pentru ${location.category} cu ${location.specialist} în Google Maps`}>Deschide în Google Maps <span aria-hidden="true">↗</span></a><a className="button button-outline" href={`/programare?categorie=${location.category}`}>Programare {location.category}</a></div></article>; })}</div><p className="locations-note">Serviciile se desfășoară în locații diferite. Verifică adresa înainte de programare.</p><PageCta /></main></PageChrome>; }
