'use client';

import { useState } from 'react';
import { services, type ServiceCategory } from '@/src/data/services';

const labels: Record<ServiceCategory, string> = { lashes: 'Gene', nails: 'Unghii' };
const bookingCategory: Record<ServiceCategory, string> = { lashes: 'gene', nails: 'unghii' };

export function PriceCatalog() { const [category, setCategory] = useState<ServiceCategory>('lashes'); const items = services.filter((service) => service.category === category); return <><div className="price-tabs" role="tablist" aria-label="Categorii prețuri">{(['lashes', 'nails'] as const).map((item) => <button className={`gallery-filter${category === item ? ' is-active' : ''}`} type="button" role="tab" aria-selected={category === item} onClick={() => setCategory(item)} key={item}>{labels[item]}</button>)}</div><section className="price-category" aria-live="polite"><h2>Prețuri {labels[category].toLowerCase()}</h2><p>{category === 'lashes' ? 'Tarifele diferă în funcție de tehnică, volum, întreținere și efectul ales.' : 'Tarifele pot varia în funcție de lungime, tehnică, întreținere și opțiunile de design.'}</p><div className="price-list">{items.map((service) => <article className="price-row" key={service.id}><div><h3>{service.name}</h3><p>{service.specialist === 'dariana' ? 'Dariana' : 'Lucia'} · {service.durationMinutes ? `${service.durationMinutes} min` : 'Durată în curs de actualizare'}</p>{service.needsConfirmation && <small>Detalii în curs de actualizare</small>}</div><strong>{service.priceText ?? (service.price ? `${service.price} lei` : 'În curând')}</strong><a className="button button-primary" href={`/programare?categorie=${bookingCategory[service.category]}&serviciu=${service.id}`}>Alege</a></article>)}</div><section className="unknown-choice"><h3>Nu știu ce să aleg</h3><p>Pornește programarea cu categoria selectată și alege serviciul împreună cu specialistul.</p><a className="button button-outline" href={`/programare?categorie=${bookingCategory[category]}&serviciu=nu-stiu`}>Ajută-mă să aleg pentru {labels[category].toLowerCase()}</a></section></section></>; }
