'use client';

import { useState } from 'react';
import { services, type ServiceCategory } from '@/src/data/services';

const labels: Record<ServiceCategory, string> = { lashes: 'Gene', nails: 'Unghii' };
const bookingCategory: Record<ServiceCategory, string> = { lashes: 'gene', nails: 'unghii' };

export function ServiceCatalog() { const [filter, setFilter] = useState<'all' | ServiceCategory>('all'); const visible = filter === 'all' ? services : services.filter((service) => service.category === filter); return <><div className="category-intros"><article><h2>Gene</h2><p>Servicii create pentru o privire definită, echilibrată și adaptată fizionomiei tale, de la rezultate naturale până la efecte mai intense.</p></article><article><h2>Unghii</h2><p>Servicii pentru unghii îngrijite, rezistente și personalizate, de la întreținere și culoare până la formă și design.</p></article></div><div className="page-filters" role="group" aria-label="Filtre servicii">{(['all', 'lashes', 'nails'] as const).map((item) => <button className={`gallery-filter${filter === item ? ' is-active' : ''}`} type="button" aria-pressed={filter === item} onClick={() => setFilter(item)} key={item}>{item === 'all' ? 'Toate' : labels[item]}</button>)}</div><div className="service-catalog">{visible.map((service) => <article className="catalog-card" key={service.id}><div className="catalog-card-top"><span className="catalog-category">{labels[service.category]}</span><span className="catalog-specialist">{service.specialist === 'dariana' ? 'Dariana' : 'Lucia'}</span></div><h2>{service.name}</h2><p>{service.fullDescription ?? 'Detalii în curs de actualizare.'}</p><dl><div><dt>Durată</dt><dd>{service.durationMinutes ? `${service.durationMinutes} min` : 'Detalii în curs de actualizare'}</dd></div><div><dt>Preț</dt><dd>{service.priceText ?? (service.price ? `${service.price} lei` : 'Detalii în curs de actualizare')}</dd></div></dl>{service.needsConfirmation && <p className="confirmation-note">Detalii în curs de actualizare</p>}<a className="button button-primary" href={`/programare?categorie=${bookingCategory[service.category]}&serviciu=${service.id}`} aria-label={`Programează-te pentru ${service.name}`}>Programează-te pentru acest serviciu <span aria-hidden="true">↗</span></a></article>)}</div><section className="unknown-choice"><h2>Nu știu ce să aleg</h2><p>Poți începe programarea fără să alegi încă un serviciu. Te ajutăm să găsești varianta potrivită.</p><div className="unknown-actions"><a className="button button-outline" href="/programare?categorie=gene&serviciu=nu-stiu">Gene — ajută-mă să aleg</a><a className="button button-outline" href="/programare?categorie=unghii&serviciu=nu-stiu">Unghii — ajută-mă să aleg</a></div></section></>; }
